<?php
/**
 * Banner
 * ======
 */
echo "⚙️ Adding banner..." . PHP_EOL;
$txtWhitelist  = '## ☠️ WARNING! This file was AUTOGENERATED by zzfirewall - Do not edit directly!';
$txtWhitelist .= PHP_EOL . '## See: https://github.com/TurboLabIt/zzfirewall/';


/**
 * Allow connections from GoogleBot...
 * ===================================
 */
// https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot
const GOOGLE_WHITELIST_URL = 'https://developers.google.com/static/search/apis/ipranges/googlebot.json';
echo "⚙️ Adding from Google " . GOOGLE_WHITELIST_URL . "..." . PHP_EOL;
$txtWhitelist .= PHP_EOL . PHP_EOL . '## 🔎 Allow from GoogleBot - ' . GOOGLE_WHITELIST_URL . PHP_EOL;
$txtGoogle = file_get_contents(GOOGLE_WHITELIST_URL);

if($txtGoogle === false) {
  die("⚠️ Download from " . GOOGLE_WHITELIST_URL . " FAILED! Aborting!");
}

$arrGoogle = json_decode($txtGoogle);

if( !is_object($arrGoogle) ) {
  die("⚠️ json_decode from " . GOOGLE_WHITELIST_URL . " FAILED! Aborting!");
}

$txtGoogle = "";
foreach($arrGoogle->prefixes as $oneItem) {

  if( empty($oneItem->ipv4Prefix) ) {
    continue;
  }

  $txtGoogle .= $oneItem->ipv4Prefix . PHP_EOL;
}

$txtWhitelist .= $txtGoogle;


/**
 * Allow connections from Uptimerobot...
 * ===================================
 */
// https://uptimerobot.com/help/locations/
const UPTIMEROBOT_WHITELIST_URL = 'https://uptimerobot.com/inc/files/ips/IPv4.txt';
echo "⚙️ Adding from Uptimerobot " . UPTIMEROBOT_WHITELIST_URL . "..." . PHP_EOL;
$txtWhitelist .= PHP_EOL . PHP_EOL . '## 🔎 Allow from UptimerobotBot - ' . UPTIMEROBOT_WHITELIST_URL . PHP_EOL;
$txtUptimerobot = file_get_contents(UPTIMEROBOT_WHITELIST_URL);

if($txtUptimerobot === false) {
    die("⚠️ Download from " . UPTIMEROBOT_WHITELIST_URL . " FAILED! Aborting!");
}

$txtWhitelist .= $txtUptimerobot;


/**
 * Writing the file...
 * ===================
 */
const WHITELIST_OUT_PATH = '/usr/local/turbolab.it/zzfirewall/lists/autogen/';

$filePath = WHITELIST_OUT_PATH . 'whitelist.txt';
echo "⚙️ Writing the file to " . $filePath . "..." . PHP_EOL;
file_put_contents($filePath, $txtWhitelist);

$filePath = WHITELIST_OUT_PATH . 'google.txt';
echo "⚙️ Writing the file to " . $filePath . "..." . PHP_EOL;
file_put_contents($filePath, $txtGoogle);

echo PHP_EOL . "✅ " . basename(__FILE__, '.php') . " is DONE" . PHP_EOL;
