<?php
/**
 * Banner
 * ======
 */
echo "⚙️ Adding banner..." . PHP_EOL;
$txtBlacklist    = '## ☠️ WARNING! This file is AUTOGENERATED by zzfirewall! Do not edit!';
$txtBlacklist   .= PHP_EOL . '## See: https://github.com/TurboLabIt/zzfirewall/';


/**
 * Deny connections from some ready-to-use blacklists
 * ============================================
 */
$arrLists = [
    'https://raw.githubusercontent.com/TurboLabIt/zzfirewall/main/lists/blacklist.txt',
];

foreach($arrLists as $oneList) {

    echo "⚙️ Adding from  " . $oneList . "..." . PHP_EOL;
    $txtBlacklist   .= PHP_EOL . PHP_EOL . file_get_contents($oneList);
}


/**
 * Writing the file...
 * ===================
 */
$txtBlacklist .= PHP_EOL . PHP_EOL;
const BLACKLIST_OUT_PATH = '/usr/local/turbolab.it/zzfirewall/lists/autogen/blacklist.txt';
echo "⚙️ Writing the file to " . BLACKLIST_OUT_PATH . "..." . PHP_EOL;
file_put_contents(BLACKLIST_OUT_PATH, $txtBlacklist);

echo PHP_EOL . "✅ " .basename(__FILE__, '.php') . " is DONE" . PHP_EOL;

