#!/usr/bin/env bash
echo ""

source "/usr/local/turbolab.it/bash-fx/bash-fx.sh"
fxHeader "🛡️ Generate black, white lists"
rootCheck

fxTitle "🤝 Generate whitelist..."
echo ""
XDEBUG_MODE=off php ${SCRIPT_DIR}generate-whitelist.php
echo ""

fxTitle "🧱 Generate blacklist..."
echo ""
XDEBUG_MODE=off php ${SCRIPT_DIR}generate-blacklist.php
echo ""

fxTitle "✔️ Git commit..."
git -C ${SCRIPT_DIR}../ add ${SCRIPT_DIR}../lists/autogen/whitelist.txt
git -C ${SCRIPT_DIR}../ add ${SCRIPT_DIR}../lists/autogen/google.txt
git -C ${SCRIPT_DIR}../ add ${SCRIPT_DIR}../lists/autogen/blacklist.txt
git -C ${SCRIPT_DIR}../ commit -m"🧱 autogenerated firewall lists update"

fxTitle "☁️ Git pull and push..."
git -C ${SCRIPT_DIR}../ pull --no-edit
git -C ${SCRIPT_DIR}../ push

