<?php
require 'generate.lib.php';

echo "⚙️ Adding banner..." . PHP_EOL;
$txtWhitelist  = '## ☠️ WARNING! This file was AUTOGENERATED by zzfirewall - Do not edit directly!' . PHP_EOL;
$txtWhitelist .= '## See: https://github.com/TurboLabIt/zzfirewall/';


echo "⚙️ Allow from GoogleBot (search)..." . PHP_EOL;
// https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot
const GOOGLEBOT_URL = 'https://developers.google.com/static/search/apis/ipranges/googlebot.json';
$txtWhitelist .= PHP_EOL . PHP_EOL . '## 🔎 Allow from GoogleBot - ' . GOOGLEBOT_URL . PHP_EOL;

$txtGoogle = implode(PHP_EOL, getGoogleIpList(GOOGLEBOT_URL) ) . PHP_EOL;
$txtWhitelist .= $txtGoogle;


/**
 * Allow connections from Uptimerobot...
 * ===================================
 */
// https://uptimerobot.com/help/locations/
const UPTIMEROBOT_WHITELIST_URL = 'https://uptimerobot.com/inc/files/ips/IPv4.txt';
echo "⚙️ Adding from UptimeRobot ..." . PHP_EOL;
$txtWhitelist .= PHP_EOL . PHP_EOL . '## 🔎 Allow from UptimerobotBot - ' . UPTIMEROBOT_WHITELIST_URL . PHP_EOL;
$txtUptimerobot = file_get_contents(UPTIMEROBOT_WHITELIST_URL);

if($txtUptimerobot === false) {
    die("⚠️ Download from " . UPTIMEROBOT_WHITELIST_URL . " FAILED! Aborting!");
}

$txtWhitelist .= $txtUptimerobot;


/**
 * Allow connections from Bunny CDN...
 * ===================================
 */
// https://bunnycdn.com/api/system/edgeserverlist
const BUNNYCDN_WHITELIST_URL = 'https://bunnycdn.com/api/system/edgeserverlist';
echo "⚙️ Adding from Bunny CDN..." . PHP_EOL;
$txtWhitelist .= PHP_EOL . PHP_EOL . '## 🔎 Allow from Bunny CDN - ' . BUNNYCDN_WHITELIST_URL . PHP_EOL;
$txtJson = file_get_contents(BUNNYCDN_WHITELIST_URL);

if($txtUptimerobot === false) {
    die("⚠️ Download from " . BUNNYCDN_WHITELIST_URL . " FAILED! Aborting!");
}

$oJson = json_decode($txtJson);
if( empty($oJson) ) {
    die("⚠️ JSON parsing of " . BUNNYCDN_WHITELIST_URL . " FAILED! Aborting!");
}

foreach($oJson as $ip) {
    $txtWhitelist .= (string)$ip . PHP_EOL;
}


/**
 * Writing the file...
 * ===================
 */
const WHITELIST_OUT_PATH = '/usr/local/turbolab.it/zzfirewall/lists/autogen/';

$filePath = WHITELIST_OUT_PATH . 'whitelist.txt';
echo "⚙️ Writing the file to " . $filePath . "..." . PHP_EOL;
file_put_contents($filePath, $txtWhitelist);

$filePath = WHITELIST_OUT_PATH . 'google-search.txt';
echo "⚙️ Writing the file to " . $filePath . "..." . PHP_EOL;
file_put_contents($filePath, $txtGoogle);


echo "⚙️ Writing all Google IP list (all services, including public cloud) - not whitelisted..." . PHP_EOL;
const GOOGLE_URL = 'https://www.gstatic.com/ipranges/goog.json';
$txtGoogleAll = implode(PHP_EOL, getGoogleIpList(GOOGLE_URL) ) . PHP_EOL;

$filePath = WHITELIST_OUT_PATH . 'google.txt';
echo "⚙️ Writing the file to " . $filePath . "..." . PHP_EOL;
file_put_contents($filePath, $txtGoogleAll);


echo PHP_EOL . "✅ " . basename(__FILE__, '.php') . " is DONE" . PHP_EOL;
